---
title: "Tutorial: GLM & AIC"
author: "BIOL 414/514"
date: "Quantitative Analysis of Vertebrate Populations"
output:
  tufte::tufte_handout:
    df_print: kable
  tufte::tufte_html: default
urlcolor: blue
bibliography: bibliography.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r, echo = FALSE}
library(tufte)
```


`r newthought("Learning Objectives:")`




```{r}
trout <- read.csv("Data/Trout/regional_occupancy_data.csv", stringsAsFactors = FALSE)
str(trout)
```


```{r}
covariates <- readRDS("Data/Trout/covariates.RData")
str(covariates)
```

## Select covariates and join with trout data

```{r}

```




## Small Data 

From Kery blue book - chp 18 black adders?

```{r}
library(dplyr)
N <- 30
x1 <- rnorm(N, 0, 1)
x2 <- rnorm(N, 0, 0.8)

b0 <- log(2)
b1 <- 1.2
b2 <- -0.8

log_lam <- b0 + b1 * x1 + b2 * x2
lam <- exp(log_lam)
set.seed(13984)
counts <- rpois(30, lam)
pres <- ifelse(counts > 0, 1, 0)

df <- data.frame(counts, pres, x1, x2)
```


```{r}
df

colnames(df) <- c("count", "pres", "veg", "temp")

cor(df$veg, df$temp)

lm1 <- lm(count ~ veg + temp, data = df)
plot(lm1)

glm1 <- glm(count ~ 1 + veg + temp, data = df, family = poisson(link = "log"))

plot(glm1)

summary(glm1)

glm2 <- glm(count ~ 1 + veg, data = df, family = poisson)
summary(glm2)

AIC(glm1)
AIC(glm2)


glm3 <- glm(pres ~ 1 + veg + temp, data = df, family = binomial(link = "logit"))
summary(glm3)


exp(4.1589) / (1 + exp(4.1589))
```


