---
title: "Homework 2"
author: "Quantitative Analysis of Vertebrate Populations"
output: pdf_document
---

## 1. Using the `iris` data, make a new dataframe called `iris_petal` with just the petal length and width columns.


## 2. Now add a new column to `iris_petal` called `Random` filled with normally distributed random numbers.

## 3. Display the first 15 rows of the `iris_petal` dataframe.

## 4. Print a summary of the `iris_petal` dataframe.

## 5. Select just the values of `Petal.Length` greater than the mean petal length. Then print the new summary.

## 6. Read a file into R and save the dataframe as an object. Be sure to use `stringsAsFactors = FALSE`. 

## 7. Make a scatterplot matrix of three variables from the new dataframe.

## 8. Run a linear regression and print the summary table.

## 9. Are the linear model assumptions met and how do you know (Hint: make diagnostic plots using `plot(Model_Name)` and interpret the output. You won't lose points if you correctly explain the plots even if I disagree with your judgement on whether things are normal or homogenous enough.