---
title: "Homework 1: R Introduction"
author: "Your_Name_Here"
output: pdf_document
---

*Adapted from University of Tennessee Biometry course by Dr. Jim Fordyce*

Turn in via blackboard next Friday by the end of the day. please title the document **hw1_yourlastname_yourfirstname**. Ideally it will be a PDF file generated from knitting an RMarkdown document.


## 1. Assign to a vector called X the values 1,3,5,6,7, and 9. Assign to a vector called Y the values 2,7,4,5,2 and 12.



 
## 2. Combine the two vectors together as one large vector called Z.



## 3. Create a new vector that includes all the values in Z that are less than 6.



## 4. Using R functions, calculate the mean of Z.



## 5. Create an matrix where the columns are X and Y. Assign this matrix to an object called mat1.



## 6. Using the R function `rowSums`, calculate the sum of each row.



## 7. Calculate the mean of the rows of mat1 and add this as a third column.



## 8. Extract the value of mat1 at the second row and first column.



## 9. Write mat1 to a .csv file.



## 10. Read the .csv file and assign it to an object called mat_new.




## 11 Show that the third number in the first column of `mat_new` is equal to the fourth number in the second column.



## 12 Make 'mat1' a data frame.



## 13 Using R functions, calculate the length of X.



## 14 Assign the name "mean" to the third column of mat1.


## 15 Create a sequence of numbers from -10 to 10 with intevals of 0.5 using R functions. Assign it to an object and calculate the sum of the values.




