---
title: "Known Fate Activity"
author: "Quantitative Analysis of Vertebrate Populations"
output:
  pdf_document: default
  ioslides_presentation:
    css: styles.css
  beamer_presentation: default
---

## 1. What are the assumptions of known fate models of estimating survival?

\vspace{50mm}

## 2. Desribe three types of data or things that can be estimated with a known fate approach.

\vspace{100mm}

## 3. What are the probability statements for these known fate capture histories of survival? Imagine they are weekly relocations of turtles with radio transmitters

* 11110
* 11111
* 10
* 110

\vspace{20mm}

## 4. Imagine we had radiotransmitters on 30 woodfrogs at each of two sites. At then end of the 50 days of radiotracking (livespan of a battery in a sufficiently sized transmitter), we had 22 alive at site one and 17 alive at site two. Estimate the survival in each population (site).

\vspace{60mm}

## 5. What is censoring and how does it influence survival estimation? What is the difference between left and right censoring?

\vspace{60mm}

## 6. What does the Kaplan-Meier model attempt to account for relative to the simple estimator of $\hat S = \frac{y}{n}$? What are the assumptions of this model?

\newpage

## 7. Calculate the survival rates for each decade from Frostburg, MD cemetery data (on canvas). Use the females pre-1950.

\vspace{100mm}

## 8. What are things you're unsure about in this chapter? Think about how you would sent up a known fate study. What are things you would like clarified further before starting your study?

\vspace{60mm}


