---
title: "Getting Started with Quantitative Analysis in R"
author: "Daniel Hocking"
date: "9/27/2018"
output: pdf_document
---

## Download R

R is free open source software designed for doing statisical analyses. It has become the *lingua franca* of statistics and ecological and wildlife statistics. It is also an Object-Oriented Programming Language. This means that R is for much more than statistics. You can do data analysis but also data manipulation, data organization, and interact with other programming languages. If you can dream it, you can do it in R. There are other languages that are much better for particular tasks but for this course we will use R and it will take you a VERY long way.

You can get R at:

It will work on any computer whether you are running Windows, Mac OS, or Linux.

Learning a new language is challenging. R has a very steep learning curve, so it might be challenging and frustrating at times but it will be rewarding and helpful in the end. **Stick with it and ask questions and get help before you give up. We are in this together!**

## Download RStudio

RStudio is also free and it's an amazing interface for R (technically an Integrated Development Environment or IDE). You need to have R installed but the RStudio is helpful interface that provide file organization, object lists, scripts in a variety of formats, code error checking, and code formatting.

You can download RStudio on any computer:

## File Types

R, RMarkdown, RNotebooks, etc.

## Setup

When starting any new code you will want to have your R scripts, RMarkdown files, Data, and RProjects all in a single folder on your computer. The RMD files and RProj files should be in the main part of the folder but other things can be in subfolders (`Data/` folder, `Results/` folder, `Figures/` folder, etc.)




