---
title: "Abundance Accounting for Imperfect Detection: N-Mixture Model"
author: "Quantitative Analysis of Vertebrate Populations"
output: pdf_document
---

**Adapted from Kery 2010. Introduction to WinBUGS for Ecologists**

### 21.2. Data generation

```{r}
library(jagsUI)
n.site <- 200
vege <- sort(runif(n = n.site, min = -1.5, max =1.5))

alpha.lam <- 2				# Intercept
beta1.lam <- 2				# Linear effect of vegetation
beta2.lam <- -2				# Quadratic effect of vegetation
lam <- exp(alpha.lam + beta1.lam * vege + beta2.lam * (vege^2))

par(mfrow = c(2,1))
plot(vege, lam, main = "", xlab = "", ylab = "Expected abundance", las = 1)

N <- rpois(n = n.site, lambda = lam)
table(N)				# Distribution of abundances across sites
sum(N > 0) / n.site			# Empirical occupancy

plot(vege, N, main = "", xlab = "Vegetation cover", ylab = "Realized abundance")
points(vege, lam, type = "l", lwd = 2)
```

```{r}
par(mfrow = c(2,1))
alpha.p <- 1				# Intercept
beta.p <- -4				# Linear effect of vegetation
det.prob <- exp(alpha.p + beta.p * vege) / (1 + exp(alpha.p + beta.p * vege))
plot(vege, det.prob, ylim = c(0,1), main = "", xlab = "", ylab = "Detection probability")

expected.count <- N * det.prob
plot(vege, expected.count, main = "", xlab = "Vegetation cover", ylab = 
"Apparent abundance", ylim = c(0, max(N)), las = 1)
points(vege, lam, type = "l", col = "black", lwd = 2) # Truth
```

```{r}
R <- n.site
T <- 3					# Number of replicate counts at each site
y <- array(dim = c(R, T))

for(j in 1:T){
    y[,j] <- rbinom(n = n.site, size = N, prob = det.prob)
}
# y

sum(apply(y, 1, sum) > 0)		# Apparent distribution (proportion occupied sites)
sum(N > 0)				# True occupancy

C <- c(y)

site = 1:R				# ‘Short’ version of site covariate
site.p <- rep(site, T)			# ‘Long’ version of site covariate
vege.p <- rep(vege, T)			# ‘Long’ version of vegetation covariate
# cbind(C, site.p, vege.p)		# Check that all went right

max.count <- apply(y, 1, max)
naive.analysis <- glm(max.count ~ vege + I(vege^2), family = poisson)
summary(naive.analysis)
lin.pred <- naive.analysis$coefficients[1] + naive.analysis$coefficients[2] * vege + naive.analysis$coefficients[3] * (vege*vege)
```

```{r}
par(mfrow = c(1,1))
plot(vege, max.count, main = "", xlab = "Vegetation cover", ylab = "Abundance or count", 
ylim = c(0,max(N)), las = 1)
points(vege, lam, type = "l", col = "black", lwd = 2)
points(vege, exp(lin.pred), type = "l", col = "red", lwd = 2)
```


### 21.3. Analysis using WinBUGS

```{r}
# Define model with new uniform priors
sink("BinMix.txt")
cat("
model {

# Priors (new)
 # alpha.lam ~ dunif(-10, 10)
 # beta1.lam ~ dunif(-10, 10)
 # beta2.lam ~ dunif(-10, 10)
 # alpha.p ~ dunif(-10, 10)
 # beta.p ~ dunif(-10, 10)

alpha.lam ~ dnorm(0, 0.01)
beta1.lam ~ dnorm(0, 0.01)
beta2.lam ~ dnorm(0, 0.01)
alpha.p ~ dnorm(0, 0.01)
beta.p ~ dnorm(0, 0.01)


# Likelihood
# Biological model for true abundance
 for (i in 1:R) {
   N[i] ~ dpois(lambda[i])
   log(lambda[i]) <- alpha.lam + beta1.lam * vege[i] + beta2.lam * vege2[i]
 }

# Observation model for replicated counts
 for (i in 1:n) {
   C[i] ~ dbin(p[i], N[site.p[i]])
   lp[i] <- alpha.p + beta.p * vege.p[i]
   p[i] <- exp(lp[i])/(1+exp(lp[i]))
 }

# Derived quantities
 totalN <- sum(N[])

# Assess model fit using Chi-squared discrepancy
 for (i in 1:n) {
# Compute fit statistic for observed data
     eval[i]<-p[i]*N[site.p[i]]
     E[i] <- pow((C[i] - eval[i]),2) / (eval[i] + 0.5)
# Generate replicate data and compute fit stats for them
     C.new[i] ~ dbin(p[i], N[site.p[i]])
     E.new[i] <- pow((C.new[i] - eval[i]),2) / (eval[i] + 0.5)
 }
 fit <- sum(E[])
 fit.new <- sum(E.new[])
}
",fill=TRUE)
sink()

# Bundle data
R = dim(y)[1]
n = dim(y)[1] * dim(y)[2]
vege2 = (vege * vege)
win.data <- list(R = R, vege = vege, vege2 = vege2, n = n, C = C, site.p = site.p, vege.p = vege.p)

# Inits function
Nst <- apply(y, 1, max) + 1
inits <- function(){list(N = Nst, alpha.lam=rnorm(1, 0, 1), beta1.lam=rnorm(1, 0, 1), 
beta2.lam=rnorm(1, 0, 1), alpha.p=rnorm(1, 0, 1), beta.p=rnorm(1, 0, 1))}

# Parameters to estimate
params <- c("N", "totalN", "alpha.lam", "beta1.lam", "beta2.lam", 
"alpha.p", "beta.p", "fit", "fit.new")

# MCMC settings
nc <- 3
nb <- 10000
ni <- 6000
nt <- 5

# Start Gibbs sampler
out <- jags(win.data, inits, params, "BinMix.txt", n.chains=nc, n.adapt = nb, n.iter=ni, n.thin=nt, parallel = TRUE, n.cores = 3, bugs.format = TRUE)

print(out, dig = 3)
which(out$summary[,8] > 1.1)

hist(out$sims.list$beta.p, col = "grey", main = "", xlab = "")

plot(out$sims.list$fit, out$sims.list$fit.new, main = "", xlab = 
"Discrepancy measure for actual data set", 
ylab = "Discrepancy measure for perfect data sets")
abline(0,1, lwd = 2, col = "black")

mean(out$sims.list$fit.new > out$sims.list$fit)

cat("\n *** Our estimate of truth *** \n\n")
print(out, dig = 2)

cat("\n *** Compare with known truth ***\n\n")
alpha.lam  ;  beta1.lam  ;  beta2.lam  ;   alpha.p  ;  beta.p
sum(N) 					# True total population size across all sites
sum(apply(y, 1, max))			# Sum of site max counts

par(mfrow = c(3,2))
hist(out$sims.list$alpha.lam, col = "grey", main = "alpha.lam", xlab = "")
abline(v = alpha.lam, lwd = 3, col = "black")
hist(out$sims.list$beta1.lam, col = "grey", main = "beta1.lam", xlab = "")
abline(v = beta1.lam, lwd = 3, col = "black")
hist(out$sims.list$beta2.lam, col = "grey", main = "beta2.lam", xlab = "")
abline(v = beta2.lam, lwd = 3, col = "black")
hist(out$sims.list$alpha.p, col = "grey", main = "alpha.p", xlab = "")
abline(v = alpha.p, lwd = 3, col = "black")
hist(out$sims.list$beta.p, col = "grey", main = "beta.p", xlab = "")
abline(v = beta.p, lwd = 3, col = "black")
hist(out$sims.list$totalN, col = "grey", , main = "Total N", xlab = "")
abline(v = sum(N), lwd = 3, col = "black")


sel <- sort(sample(1:200, size = 4))
sel

par(mfrow = c(2,2))
hist(out$sims.list$N[,sel[1]], col = "grey", xlim = c(Nst[sel[1]]-1, 
max(out$sims.list$N[,sel[1]])), main = "Site 48", xlab = "")
abline(v = Nst[sel[1]]-1, lwd = 3, col = "red")

hist(out$sims.list$N[,sel[2]], col = "grey", xlim = c(Nst[sel[2]]-1, 
max(out$sims.list$N[,sel[2]])), main = "Site 95", xlab = "")
abline(v = Nst[sel[2]]-1, lwd = 3, col = "red")

hist(out$sims.list$N[,sel[3]], col = "grey", xlim = c(Nst[sel[3]]-1, 
max(out$sims.list$N[,sel[3]])), main = "Site 134", xlab = "")
abline(v = Nst[sel[3]]-1, lwd = 3, col = "red")

hist(out$sims.list$N[,sel[4]], col = "grey", xlim = c(Nst[sel[4]]-1, 
max(out$sims.list$N[,sel[4]])) , main = "Site 137", xlab = "")
abline(v = Nst[sel[4]]-1, lwd = 3, col = "red")

y[sel,]

N[sel]

print(out$mean$N[sel], dig = 3)

par(mfrow = c(1,1))
plot(vege, N, main = "", xlab = "Vegetation cover", ylab = "Abundance", 
las = 1, ylim = c(0,max(N)))
points(sort(vege), lam[order(vege)], type = "l", col = "black", lwd = 2)
points(vege, exp(lin.pred), type = "l", col = "red", lwd = 2)
BinMix.pred <- exp(out$mean$alpha.lam + out$mean$beta1.lam * vege + out$mean$beta2.lam * (vege*vege))
points(vege, BinMix.pred, type = "l", col = "blue", lwd = 2)

```

