---
title: "Homework 1: R Introduction"
author: "Your_Name_Here"
output: pdf_document
---

Turn in via Canvas next Friday by the end of the day. please title the document **hw1_yourlastname_yourfirstname**. Submit both the .Rmd file and either a knitted pdf, html, or doc file.


## 1. Assign to a vector called X the values 1,3,5,6,7, and 9. Assign to a vector called Y the values 2,7,4,5,2 and 12.

```{r}

```

 
## 2. Combine the two vectors together as one large vector called Z.



## 3. Create a new vector that includes all the values in Z that are less than 6.



## 4. Using R functions, calculate the mean of Z.



## 5. Create an matrix where the columns are X and Y. Assign this matrix to an object called mat1.



## 6. Using the R function `rowSums`, calculate the sum of each row. You may have to look up how to use this function.



## 7. Calculate the mean of the rows of mat1 and add this as a third column.



## 8. Extract the value of mat1 at the second row and first column.



## 9. Write mat1 to a .csv file.



## 10. Make 'mat1' a data frame.

